name: Due Date Checker

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6:00 AM UTC
  workflow_dispatch:

jobs:
  due-date-check:
    name: Run /api/sync-due-check
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel due date checker
        run: curl -s https://notion-syncer.vercel.app/api/sync-due-check
