name: Due Date Checker

on:
  schedule:
    - cron: '0 */4 * * *'   # ← runs every 4 hours
  workflow_dispatch:

jobs:
  due-date-check:
    name: Run /api/sync-due-check
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel due date checker
        run: curl -s https://notion-syncer.vercel.app/api/sync-due-check
