name: Sync Failure Alert

on:
  workflow_run:
    workflows: ["Sync Assignments"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 🚨 Notion Sync Failed!
          to: your-email@example.com
          from: Notion Syncer
          body: |
            The GitHub workflow "Sync Assignments" has failed. Please check the logs.
